### ISSUE TITLE
Вопрос 1. Назначение кода

### ISSUE THREAD

**Issue by nzhukov** [python-advance/sem6-t1-Yalkinzsun#1]
https://github.com/python-advance/sem6-t1-Yalkinzsun/blob/6acdbf40b8229043514ee839c77fc8496c699f7f/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0/%D0%98%D0%BD%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D0%BD%D1%8B%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F/1.2/guestbookpackage/__init__.py#L2

Какой функционал реализует этот фрагмент кода?

**Comment by Yalkinzsun** [comment]
Данный фрагмент кода предназначен для упрощения импортирования пакета из любого места текущего каталога без указания абсолютного адреса

**Comment by nzhukov** [comment]
При импорте вашего пакета происходит ошибка: 
```sh
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import gb
  File "/Users/northbug/Development/gb/__init__.py", line 2, in <module>
    sys.path.append(get_script_dir())
NameError: name 'get_script_dir' is not defined
```
Код необходимо сделать полностью работоспособным.
